import type {
  CloudNat,
  CloudRouter,
  ComputeInstance,
  FirewallRule,
  NetworkArchitecture,
  Subnet,
  VpcNetwork,
} from "@/domain/models/gcp-network";
import { getComponentsByKind } from "@/domain/models/selectors";

function table(headers: string[], rows: string[][]) {
  const header = `| ${headers.join(" | ")} |`;
  const divider = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((row) => `| ${row.join(" | ")} |`).join("\n");
  return [header, divider, body].join("\n");
}

export function generateMarkdownDocumentation(architecture: NetworkArchitecture) {
  const networks = getComponentsByKind<VpcNetwork>(architecture, "vpc");
  const subnets = getComponentsByKind<Subnet>(architecture, "subnet");
  const instances = getComponentsByKind<ComputeInstance>(architecture, "vmInstance");
  const firewalls = getComponentsByKind<FirewallRule>(architecture, "firewallRule");
  const routers = getComponentsByKind<CloudRouter>(architecture, "cloudRouter");
  const nats = getComponentsByKind<CloudNat>(architecture, "cloudNat");

  return `# ${architecture.name}

${architecture.description ?? "Generated by the GCP Virtual Network Planner."}

> This document was generated from an educational planning model and approximates GCP behavior. It is not a replacement for Google Cloud Network Intelligence Center or production verification workflows.

## VPC Networks

${table(
  ["Name", "Routing Mode", "MTU", "Shared VPC Host"],
  networks.map((network) => [network.name, network.routingMode, String(network.mtu), network.isSharedVpcHost ? "Yes" : "No"])
)}

## Subnets

${table(
  ["Name", "Region", "CIDR", "VPC", "Private Google Access", "Flow Logs"],
  subnets.map((subnet) => [
    subnet.name,
    subnet.region ?? "-",
    subnet.cidr,
    subnet.vpcId ?? "-",
    subnet.privateGoogleAccess ? "Enabled" : "Disabled",
    subnet.flowLogs ? "Enabled" : "Disabled",
  ])
)}

## Compute Instances

${table(
  ["Name", "Zone", "Subnet", "External IP", "Tags", "Exposed Ports"],
  instances.map((instance) => [
    instance.name,
    instance.zone,
    instance.subnetId ?? "-",
    instance.hasExternalIp ? "Yes" : "No",
    instance.networkTags.join(", ") || "-",
    instance.exposedPorts.join(", ") || "-",
  ])
)}

## Firewall Rules

${table(
  ["Name", "Direction", "Action", "Protocol", "Ports", "Source Ranges", "Target Tags"],
  firewalls.map((rule) => [
    rule.name,
    rule.direction,
    rule.action,
    rule.protocol,
    rule.ports.join(", ") || "-",
    rule.sourceRanges.join(", ") || "-",
    rule.targetTags.join(", ") || "-",
  ])
)}

## Cloud Router and NAT

${table(
  ["Component", "Region", "VPC / Router", "Scope"],
  [
    ...routers.map((router) => [router.name, router.region ?? "-", router.vpcId ?? "-", "Cloud Router"]),
    ...nats.map((nat) => [
      nat.name,
      nat.region ?? "-",
      nat.routerId ?? nat.vpcId ?? "-",
      nat.appliesToAllSubnets ? "All subnets" : nat.subnetIds.join(", ") || "No subnets selected",
    ]),
  ]
)}
`;
}
